import {describe,it,expect,vi} from "vitest";
import {initialNmtLedger,reserveNmtLedger,validateNmtLedger,trackingOnlyMigration,validateNmtPolicyHistory,nmtBudgetMode,normalizeNmtBudgetMode,NMT_LIMITS} from "./nmt-budget.js";
import {NMT_TEST_PROJECT as projectId,NMT_TEST_ACCOUNT,NMT_RUNTIME_ACCOUNT,NMT_TEST_BILLING} from "./nmt-isolation.js";
import {ControlledNmtClient} from "./nmt-controlled-client.js";
const before={...initialNmtLedger(projectId),used:14484,reservations:114,categories:{smoke:3676,regression:9474,verification:0,retest:1334,manual:0}};
const migration=()=>trackingOnlyMigration(before,projectId,"2026-09-25T00:00:00.000Z");
describe("explicit dev-only tracking policy",()=>{
 it("preserves exact accumulated counters and records both policies",()=>{const {ledger,history}=migration();expect(before.version).toBe(1);expect(ledger).toMatchObject({version:2,mode:"tracking-only",limit:null,categoryLimits:null,used:14484,reservations:114,categories:before.categories});expect(history.before).toEqual(before);expect(history.after).toEqual(ledger);expect(validateNmtPolicyHistory(history,ledger)).toEqual(history);expect(nmtBudgetMode(ledger,projectId)).toBe("tracking-only");expect(nmtBudgetMode(before,projectId)).toBe("capped");});
 it("counts beyond all old limits with unchanged categories and safe integers",()=>{let {ledger}=migration();for(const category of Object.keys(NMT_LIMITS) as Array<keyof typeof NMT_LIMITS>)ledger=reserveNmtLedger(ledger,projectId,category,200000) as typeof ledger;expect(ledger.used).toBe(1014484);expect(ledger.reservations).toBe(119);expect(ledger.categories.manual).toBe(200000);expect(validateNmtLedger(ledger,projectId)).toEqual(ledger);});
 it.each(["production","line-auto-translate-bot","line-auto-translate-bot-b81bd","demo-nmt-budget"])("refuses tracking migration or use outside exact dev: %s",project=>{expect(()=>trackingOnlyMigration(initialNmtLedger(project),project,"2026-09-25")).toThrow();expect(()=>validateNmtLedger({...migration().ledger,projectId:project},project)).toThrow();});
 it.each([undefined,{mode:"unlimited"},{limit:100000},{categoryLimits:{}},{migrationId:"other"},{version:1},{used:14485},{reservations:-1},{categories:{}}])("rejects absent or corrupted tracking shape %j",patch=>{const value=patch===undefined?undefined:{...migration().ledger,...patch};expect(()=>validateNmtLedger(value,projectId)).toThrow();});
 it("retains capped defaults and rejects policy override on v1",()=>{expect(()=>reserveNmtLedger(initialNmtLedger(projectId),projectId,"manual",10001)).toThrow("exhausted");expect(()=>validateNmtLedger({...before,mode:"tracking-only"},projectId)).toThrow();expect(()=>trackingOnlyMigration(migration().ledger,projectId,"2026-09-25")).toThrow();expect(()=>normalizeNmtBudgetMode("unlimited")).toThrow();expect(normalizeNmtBudgetMode(undefined)).toBe("capped");});
 it.each([0,-1,Infinity,NaN,0.1])("rejects invalid reservation %s",n=>expect(()=>reserveNmtLedger(migration().ledger,projectId,"manual",n)).toThrow());
 it("fails closed before numeric overflow",()=>{const {ledger}=migration();expect(()=>reserveNmtLedger({...ledger,reservations:Number.MAX_SAFE_INTEGER},projectId,"manual",1)).toThrow();expect(()=>reserveNmtLedger({...ledger,used:Number.MAX_SAFE_INTEGER,categories:{smoke:Number.MAX_SAFE_INTEGER,regression:0,verification:0,retest:0,manual:0}},projectId,"manual",1)).toThrow();});
 it("history validation is independent of Firestore map key ordering",()=>{const {ledger,history}=migration();const reorder=(x:unknown):unknown=>x&&typeof x==="object"?Object.fromEntries(Object.entries(x).reverse().map(([k,v])=>[k,reorder(v)])):x;expect(()=>validateNmtPolicyHistory(reorder(history),ledger)).not.toThrow();});
 it("refuses missing/tampered history and counters lower than migration baseline",()=>{const {ledger,history}=migration();for(const value of [undefined,{}, {...history,changedAt:"invalid"},{...history,after:{...ledger,used:1}},{...history,projectId:"production"}])expect(()=>validateNmtPolicyHistory(value,ledger)).toThrow();expect(()=>validateNmtPolicyHistory(history,{...ledger,used:0,reservations:0,categories:{smoke:0,regression:0,verification:0,retest:0,manual:0}})).toThrow("regression");});
 it("still reserves once before provider failure, with no refund or retry",async()=>{let ledger=reserveNmtLedger(migration().ledger,projectId,"smoke",100000);const events:string[]=[];const send=vi.fn(async()=>{events.push("send");throw Error("provider timeout");});const client=new ControlledNmtClient({translateText:send},{async reserve(category,characters){events.push("reserve");ledger=reserveNmtLedger(ledger,projectId,category,characters);}},"smoke",async()=>({projectId,principal:NMT_TEST_ACCOUNT,runtimeAccount:NMT_RUNTIME_ACCOUNT,billingEnabled:true,billingAccount:"billingAccounts/"+NMT_TEST_BILLING}));const parent="projects/"+projectId+"/locations/global";await expect(client.translateText({parent,model:parent+"/models/general/nmt",contents:["😀甲"],mimeType:"text/html",sourceLanguageCode:"zh-TW",targetLanguageCode:"vi"},{timeout:15000,retry:{retryCodes:[]}})).rejects.toThrow();expect(events).toEqual(["reserve","send"]);expect(send).toHaveBeenCalledTimes(1);expect(ledger.used).toBe(114486);expect(ledger.reservations).toBe(116);});
});

it("tracking mode does not relax the 30000-codepoint single-request limit",async()=>{const send=vi.fn(),reserve=vi.fn(),parent="projects/"+projectId+"/locations/global";const client=new ControlledNmtClient({translateText:send},{reserve},"manual",async()=>({projectId,principal:NMT_TEST_ACCOUNT,runtimeAccount:NMT_RUNTIME_ACCOUNT,billingEnabled:true,billingAccount:"billingAccounts/"+NMT_TEST_BILLING}));await expect(client.translateText({parent,model:parent+"/models/general/nmt",contents:["x".repeat(30001)],mimeType:"text/html",sourceLanguageCode:"zh-TW",targetLanguageCode:"vi"},{timeout:15000,retry:{retryCodes:[]}})).rejects.toThrow("request_validation");expect(reserve).not.toHaveBeenCalled();expect(send).not.toHaveBeenCalled();});
