import {expect,it,vi} from "vitest";
import {prepareLlmContext} from "./nmt-context.js";
import {createContextLlmHtml} from "./nmt-context-html.js";
import {NmtGlossaryTranslator} from "./nmt-glossary-translator.js";
const options={projectId:'test-project',location:'us-central1',glossaryZhEn:'projects/test-project/locations/us-central1/glossaries/zh-en',glossaryEnZh:'projects/test-project/locations/us-central1/glossaries/en-zh-v9'};
async function translate(source:string,output:string){const send=vi.fn(async()=>[{glossaryTranslations:[{translatedText:output}]}] as [{glossaryTranslations:Array<{translatedText:string}>}]);try{return await new NmtGlossaryTranslator(options,{translateText:send}).translate(source,'en','zh-TW');}finally{expect(send).toHaveBeenCalledTimes(1);}}
it.each(['FIBC bulk bag','FIBC bulk bags','FIBC bag','FIBC bags'])('leaves the complete ordinary-glossary phrase visible: %s',phrase=>{const prepared=prepareLlmContext('Use '+phrase+'.',[],[],'zh-TW'),wire=createContextLlmHtml(prepared);expect(wire.encode()).toContain('Use '+phrase+'.');expect(wire.encode()).not.toContain('<span');expect(prepared.occurrences.filter(o=>o.kind==='packaging-code')).toHaveLength(1);});
it.each(['The FIBC code is on the label.','Use FIBC bag-load.','Copy exactly: FIBC bags.'])('retains standalone, unknown-compound and copy-exact FIBC protection: %s',source=>{expect(createContextLlmHtml(prepareLlmContext(source,[],[],'zh-TW')).encode()).toMatch(/<span[^>]+>FIBC<\/span>/);});
it.each(['FIBC大袋','FIBC袋','FIBC噸袋','FIBC貨櫃袋','貨櫃袋FIBC'])('accepts a complete bag noun without manufacturing it: %s',noun=>{const prepared=prepareLlmContext('Use FIBC bulk bags.',[],[],'zh-TW');expect(()=>createContextLlmHtml(prepared).decode('<div id="p0">使用'+noun+'。</div>')).not.toThrow();});
it.each(['貨櫃FIBC','FIBC貨櫃','集裝箱FIBC','FIBC集裝箱','容器FIBC','FIBC容器','FIBC','集裝袋'])('rejects container reversal or missing source acronym/bag: %s',noun=>{const prepared=prepareLlmContext('Use FIBC bulk bags.',[],[],'zh-TW');expect(()=>createContextLlmHtml(prepared).decode('<div id="p0">使用'+noun+'。</div>')).toThrow();});
it('retains each FIBC occurrence and paragraph ownership',()=>{const wire=createContextLlmHtml(prepareLlmContext('Use FIBC bags.\nUse FIBC bulk bags.',[],[],'zh-TW'));expect(()=>wire.decode('<div id="p0">使用FIBC袋。</div><div id="p1">使用FIBC大袋。</div>')).not.toThrow();for(const raw of ['<div id="p0">使用FIBC袋及FIBC袋。</div><div id="p1">使用大袋。</div>','<div id="p0">使用FIBC袋。</div><div id="p1">使用大袋。</div>'])expect(()=>wire.decode(raw)).toThrow();});
it.each(['貨櫃FIBC','FIBC貨櫃'])('rejects live container order in full translator: %s',async noun=>{await expect(translate('Use FIBC bulk bags,600 kg per bag.','<div id="p0">使用'+noun+'，每袋600公斤。</div>')).rejects.toThrow('packaging_object_changed');});
it.each(['FIBC大袋','FIBC貨櫃袋','貨櫃袋FIBC'])('preserves bag compounds and quantity in full translator: %s',async noun=>{await expect(translate('Use FIBC bulk bags,600 kg per bag.','<div id="p0">使用'+noun+'，每袋600公斤。</div>')).resolves.toContain(noun);});

it.each(['FIBC散裝袋','FIBC包裝袋','散裝袋 FIBC','包裝袋 FIBC','FIBC散装袋','FIBC包装袋'])('R3 accepts complete natural packing nouns on the source occurrence: %s',async noun=>{await expect(translate('Use FIBC bulk bags,600 kg per bag.','<div id="p0">使用'+noun+'，每袋600公斤。</div>')).resolves.toContain('600 kg');});
it.each(['FIBC散裝','FIBC包裝','散裝FIBC','包裝FIBC','FIBC散裝箱','FIBC包裝箱'])('R3 still requires the complete bag noun: %s',async noun=>{await expect(translate('Use FIBC bulk bags,600 kg per bag.','<div id="p0">使用'+noun+'，每袋600公斤。</div>')).rejects.toThrow('packaging_object_changed');});
it.each(['每箱600公斤','每袋600.0公斤','每袋500公斤'])('R3 natural bag noun does not excuse changed denominator/precision/amount: %s',async weight=>{await expect(translate('Use FIBC bulk bags,600 kg per bag.','<div id="p0">使用FIBC散裝袋，'+weight+'。</div>')).rejects.toThrow();});
it('R3 keeps natural bag occurrences in their source paragraphs',async()=>{const source='Use FIBC bulk bags.\nUse FIBC bags.';await expect(translate(source,'<div id="p0">使用FIBC散裝袋。</div><div id="p1">使用FIBC包裝袋。</div>')).resolves.toContain('FIBC包裝袋');await expect(translate(source,'<div id="p0">使用FIBC散裝袋與FIBC包裝袋。</div><div id="p1">使用袋子。</div>')).rejects.toThrow();await expect(translate(source,'<div id="p0">使用FIBC散裝袋。</div><div id="p1">使用袋子。</div>')).rejects.toThrow();});

it.each([['600 kg','600公斤'],['600 lb','600磅'],['0.6 MT','0.6公噸']])('LIVE05 accepts known unit adjacent to the same source FIBC: %s',async(sourceWeight,outputWeight)=>{await expect(translate('Use '+sourceWeight+' FIBC bags.','<div id="p0">使用'+outputWeight+'FIBC袋。</div>')).resolves.toBe('使用'+sourceWeight+'FIBC袋。');});
it.each(['600.0公斤FIBC袋','500公斤FIBC袋','600磅FIBC袋','600公噸FIBC袋','600公斤FIBCX袋','600公斤FIBC-load','600kgFIBC袋','600公斤FIBC貨櫃','600公斤FIBC','600公斤袋','600公斤FIBC袋及FIBC袋'])('LIVE05 preserves precision/unit/code/noun/count boundaries: %s',async phrase=>{await expect(translate('Use 600 kg FIBC bags.','<div id="p0">使用'+phrase+'。</div>')).rejects.toThrow();});
it('LIVE05 does not admit an acronym absent from the source',async()=>{await expect(translate('Use 600 kg bags.','<div id="p0">使用600公斤FIBC袋。</div>')).rejects.toThrow();});
it('LIVE05 keeps exact occurrences in their own source paragraphs',async()=>{const source='Use 20 kg bags.\nUse 600 kg FIBC bags.';await expect(translate(source,'<div id="p0">使用20公斤袋。</div><div id="p1">使用600公斤FIBC袋。</div>')).resolves.toContain('600 kgFIBC袋');await expect(translate(source,'<div id="p0">使用20公斤FIBC袋。</div><div id="p1">使用600公斤袋。</div>')).rejects.toThrow();});
it('LIVE05 retains both adjacent occurrences rather than collapsing duplicates',async()=>{await expect(translate('Use 20 kg FIBC bags and 600 kg FIBC bags.','<div id="p0">使用20公斤FIBC袋及600公斤FIBC袋。</div>')).resolves.toContain('600 kgFIBC袋');});
it.each(['每箱600公斤FIBC袋','每袋每週600公斤FIBC袋'])('LIVE05 does not excuse a changed per-bag denominator: %s',async phrase=>{await expect(translate('Use FIBC bags,600 kg per bag.','<div id="p0">使用'+phrase+'。</div>')).rejects.toThrow('weight_denominator_changed');});
